device_type: ''
serial_no: ''
usb_port_id: ''

enable_accel: false
enable_color: true
enable_depth: false
enable_gyro: false
enable_infra1: false
enable_infra2: false

rgb_camera:
  profile: '640x480x15'
color_qos: "SYSTEM_DEFAULT"
