device_type: ''
serial_no: ''
usb_port_id: ''

enable_accel: false
enable_color: false
enable_depth: false
enable_gyro: false
enable_infra1: true
enable_infra2: true

depth_qos: "SYSTEM_DEFAULT"
depth_module:
  profile: '640x360x90'
  emitter_enabled: 0
  emitter_on_off: false