rgb_camera:
  profile: '640x480x15'
color_qos: "SYSTEM_DEFAULT"

depth_module:
  profile: '640x480x15'
  emitter_enabled: 0
  emitter_on_off: false
depth_qos: "SYSTEM_DEFAULT"
depth_info_qos: "SYSTEM_DEFAULT"

enable_infra1: false
enable_infra2: false

align_depth.enable: true
