version: '3.8'

services:
  isaac-sim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isaac_ros2_container
    environment:
      ACCEPT_EULA: "Y"
      DISPLAY: :1
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      PRIVACY_CONSENT: "Y"
    network_mode: host
    runtime: nvidia
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - isaac_user_data:/home/developer/.nvidia-omniverse
      - /home/chris/ros2_ws:/workspace/ros2_ws:cached

volumes:
  isaac_user_data:
